# Generated by Django 3.1.4 on 2021-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotocasaHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('sold', models.IntegerField(default=0)),
                ('timeonline', models.IntegerField()),
                ('price', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('nbedrooms', models.IntegerField(default=None)),
                ('nbathrooms', models.IntegerField(default=None)),
                ('size', models.IntegerField(default=None)),
                ('floor', models.IntegerField(default=None)),
                ('typology', models.IntegerField(default=None)),
                ('status', models.IntegerField(default=None, null=True)),
                ('antiquity', models.IntegerField(default=None)),
                ('elevator', models.IntegerField(default=None)),
                ('orientation', models.CharField(default=None, max_length=50, null=True)),
                ('parking', models.IntegerField(default=None)),
                ('furnished', models.CharField(default=None, max_length=50, null=True)),
                ('heating', models.CharField(default=None, max_length=50, null=True)),
                ('hotwater', models.CharField(default=None, max_length=50, null=True)),
                ('tags', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=2000, null=True)),
                ('airconditioning', models.IntegerField(default=None)),
                ('terrace', models.IntegerField(default=None)),
                ('kitchen', models.IntegerField(default=None)),
                ('parquet', models.IntegerField(default=None)),
            ],
        ),
    ]
