# Generated by Django 3.1.4 on 2020-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('timeOnline', models.IntegerField()),
                ('price', models.IntegerField()),
                ('nBedrooms', models.CharField(default='', max_length=50)),
                ('nBathrooms', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=50)),
                ('floor', models.IntegerField(default=-1)),
                ('typology', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('antiquity', models.IntegerField(default=-1)),
                ('elevator', models.IntegerField(default=-1)),
                ('orientation', models.CharField(default='', max_length=50)),
                ('parking', models.CharField(default='', max_length=50)),
                ('furnished', models.CharField(default='', max_length=50)),
                ('heating', models.CharField(default='', max_length=50)),
                ('hotWater', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
