# Generated by Django 3.1.4 on 2020-12-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='hotWater',
            new_name='hotwater',
        ),
    ]
