# Generated by Django 3.1.4 on 2021-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotocasahouse',
            name='predictedprice',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
