# Generated by Django 3.1.4 on 2020-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0002_auto_20201229_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='zone',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
