# Generated by Django 3.1.4 on 2020-12-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0003_house_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='nBathrooms',
            new_name='nbathrooms',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='nBedrooms',
            new_name='nbedrooms',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='timeOnline',
            new_name='timeonline',
        ),
    ]
