# Generated by Django 3.1.4 on 2021-01-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0004_auto_20201230_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='FotocasaHouse',
        ),
    ]
