# Generated by Django 3.1.4 on 2021-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0005_auto_20210107_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotocasahouse',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
