fotoCasaConstants = {
    'nBedroomsAverage':3,
    'nBathroomsAverage':2,
    'antiquityAverage':57,
    'sizeAverage':101,
    'zonesDict': {
        'Ciutat Meridiana': 0,
        'Zona Franca - Port': 1,
        'Trinitat Vella': 2,
        'Les Roquetes': 3,
        'Torre Baró': 4,
        'La Trinitat Nova': 5,
        'Baró de Viver': 6,
        'Verdum': 7,
        'La Prosperitat': 8,
        'El Turó de la Peira': 9,
        'Can Peguera': 10,
        'Nou Barris': 11,
        'El Bon Pastor': 12,
        'Canyelles': 13,
        'La Guineueta': 14,
        'El Carmel': 15,
        'El Besós i el Maresme': 16,
        'La Verneda i la Pau': 17,
        'Porta': 18,
        'Sant Martí de Provençals': 19,
        'Vilapicina i la Torre Llobeta': 20,
        'Sants-Badal': 21,
        'El Coll': 22,
        'La Marina del Port': 23,
        'El Congrés i els Indians': 24,
        'La Sagrera': 25,
        'La Teixonera': 26,
        'Horta': 27,
        'La Bordeta': 28,
        'El Raval': 29,
        'Sant Andreu del Palomar': 30,
        'Vallbona': 31,
        'Sant Genís dels Agudells': 32,
        'El Guinardó': 33,
        'Hostafrancs': 34,
        'La Barceloneta': 35,
        'El Poble Sec - Parc de Montjuïc': 36,
        'Sants - Montjuïc': 37,
        'Can Baró': 38,
        "El Camp de l'Arpa del Clot": 39,
        'Navas': 40,
        'Montbau': 41,
        'Sants': 42,
        'El Clot': 43,
        'Provençals del Poblenou': 44,
        "La Vall d'Hebron": 45,
        'El Baix Guinardó': 46,
        'El Parc i la Llacuna del Poblenou': 47,
        "La Font d'en Fargues": 48,
        "El Camp d'en Grassot i Gràcia Nova": 49,
        'La Font de la Guatlla': 50,
        'Vallcarca i els Penitents': 51,
        'La Clota': 52,
        'Sagrada Família': 53,
        'La Maternitat i Sant Ramon': 54,
        'Fort Pienc': 55,
        'El Poblenou': 56,
        "La Nova Esquerra de l'Eixample": 57,
        'Vila de Gràcia': 58,
        'La Salut': 59,
        'Sant Pere, Sta. Caterina i la Ribera': 60,
        'Barri de les Corts': 61,
        'Sant Antoni': 62,
        'La Vila Olímpica del Poblenou': 63,
        'Barri Gòtic': 64,
        'El Putget i el Farró': 65,
        "L'Antiga Esquerra de l'Eixample": 66,
        'Diagonal Mar i el Front Marítim del Poblenou': 67,
        "Dreta de l'Eixample": 68,
        'Vallvidrera - Tibidabo - Les Planes': 69,
        'Sant Gervasi- Galvany': 70,
        'Sarrià': 71,
        'Sant Gervasi i la Bonanova': 72,
        'Les Tres Torres': 73,
        'Sarrià - Sant Gervasi': 74,
        'Pedralbes': 75}
}