# Generated by Django 3.1.5 on 2021-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0002_fotocasahouse_predictedprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBestMLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.FloatField(default=0)),
                ('modelname', models.CharField(default='test', max_length=500)),
            ],
        ),
    ]
