# Generated by Django 3.1.5 on 2021-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0003_currentbestmlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentbestmlmodel',
            name='modelname',
        ),
        migrations.AddField(
            model_name='currentbestmlmodel',
            name='modelpath',
            field=models.CharField(default='test', max_length=1000),
        ),
    ]
