# Generated by Django 3.1.5 on 2021-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0004_auto_20210115_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbestmlmodel',
            old_name='modelpath',
            new_name='modelPath',
        ),
        migrations.AddField(
            model_name='currentbestmlmodel',
            name='modelName',
            field=models.CharField(default='FotocasaHouse', max_length=50),
        ),
    ]
