# Generated by Django 3.1.5 on 2021-01-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0005_auto_20210115_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbestmlmodel',
            old_name='modelName',
            new_name='djangoModelName',
        ),
    ]
